Jonathan Schreiber

I used python. 
To run the script I have provided, use "./memSim args"

Nothing special to note while grading. With OPT page replacement algorithm, when there was more than one page that could safely be removed, I simply found the first occurance of a safe to remove page in the page table. 
